server:
  port: 9191
  servlet:
    context-path: /shiro
    jsp:
      init-parameters:
        development: true

        #nybatis配置
mybatis:
  type-aliases-package: com.zh.shiro.entity              #指定实体类的位置
  mapper-locations: classpath:mapper/*.xml                  #mapper文件的位置
spring:
  mvc:
    view:
      prefix: /
      suffix: .jsp

  datasource:
    type: com.alibaba.druid.pool.DruidDataSource                  #数据源连接池
    url: jdbc:mysql://localhost:3306/test?serverTimezone=UTC      #url  8.0以后防止乱码需要加上
    username: root                                                #用户名
    password: 302767241                                           #密码
    driver-class-name: com.mysql.cj.jdbc.Driver                   #通常不需要设置驱动  Spring Boot会根据数据库URL识别出需要的驱动
